name = "macrometa-load-test"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "fb390958d6eff646d3a341a10cd95706"
workers_dev = true
compatibility_date = "2022-05-11"

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./shim.mjs"
